version: "3"

networks:
  hl-lab3-network:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

services:
  redis-master-a:
    image: redis:latest
    networks:
      hl-lab3-network:
        ipv4_address: 172.28.1.10
    ports:
      - "7000:7000"
    volumes:
      - ./redis-master-a:/redis
    command: redis-server /redis/redis.conf
    restart: always
  
  redis-master-b:
    image: redis:latest
    networks:
      hl-lab3-network:
        ipv4_address: 172.28.1.11
    ports:
      - "7001:7001"
    volumes:
      - ./redis-master-b:/redis
    command: redis-server /redis/redis.conf
    restart: always
        
  redis-master-c:
    image: redis:latest
    networks:
      hl-lab3-network:
        ipv4_address: 172.28.1.12
    ports:
      - "7002:7002"
    volumes:
      - ./redis-master-c:/redis
    command: redis-server /redis/redis.conf
    restart: always
  
  redis-replica-a:
    image: redis:latest
    networks:
      hl-lab3-network:
        ipv4_address: 172.28.1.13
    ports:
      - "7003:7003"
    volumes:
      - ./redis-replica-a:/redis
    command: redis-server /redis/redis.conf
    restart: always
  
  redis-replica-b:
    image: redis:latest
    networks:
      hl-lab3-network:
        ipv4_address: 172.28.1.14
    ports:
      - "7004:7004"
    volumes:
      - ./redis-replica-b:/redis
    command: redis-server /redis/redis.conf
    restart: always
  
  redis-replica-c:
    image: redis:latest
    networks:
      hl-lab3-network:
        ipv4_address: 172.28.1.15
    ports:
      - "7005:7005"
    volumes:
      - ./redis-replica-c:/redis
    command: redis-server /redis/redis.conf
    restart: always
  
  redis-cluster-creator:
    image: redis:latest
    networks:
      hl-lab3-network:
        ipv4_address: 172.28.1.16
    ports:
      - "7006:7006"
    command: redis-cli -h 172.28.1.10 -p 7000 -a dungeonmaster --cluster create 172.28.1.10:7000 172.28.1.11:7001 172.28.1.12:7002 172.28.1.13:7003 172.28.1.14:7004 172.28.1.15:7005 --cluster-replicas 1 --cluster-yes
    depends_on:
      - redis-master-a
      - redis-master-b
      - redis-master-c
      - redis-replica-a
      - redis-replica-b
      - redis-replica-c